### ISSUE TITLE
Unhandled exception: Configuration system failed to initialize

### ISSUE THREAD

**Issue by Zumochi** [EVEIPH/EVE-IPH#10]
Last night I had a power outage so my computer decided to flip on me and remove/corrupt some configuration files residing in appdata, including IPH.

However this time around, whatever I try, I am unable to fix the issue *with the latest version*.

Re-tried obviously; tried removing my settings; and I tried removing, deleting all remnants of IPH and re-installing to no avail.

However, if I re-install and **do not update**, IPH loads fine and I can add my API etc. Even if I try to update after a re-configuration it fails to start with this same exception.

**Comment by Zifrian** [comment]
I'm not sure what's going on. Did you try to reinstall .Net?

**Comment by Zumochi** [comment]
I didn't, will try tomorrow!

**Comment by Zumochi** [comment]
Re-installed .NET 3.5 and every 4.* .NET. It doesn't seem to have had any effect.

While updating IPH, the following exception often occurs as well (since having this issue): http://i.imgur.com/XTa5Eor.png

**Comment by Zifrian** [comment]
I use .Net 4. As far as the config issue, I'm not even sure what is going on. After searching around I haven't found much help. Maybe try these steps? https://www.youtube.com/watch?v=gjuipNx76uI I have a feeling it's a .Net issue since you said you re-installed, so that would get the newest set of files from IPH.

I have an idea of where that other error is coming from but not sure why it would do that. It's error handled but stranger things have happened. Send me the EVEIPH.log file and I'll see if that helps.

**Comment by Zumochi** [comment]
It seems an update a while ago fixed this issue, but it was forgotten in the void :P
