### ISSUE TITLE
Structure Saving not working properly

### ISSUE THREAD

**Issue by Keridos** [EVEIPH/EVE-IPH#112]
Please add in a way to add a custom fitting and location for a structure and to use that in all production processes easily. Seems currently saving fitting is broken.

**Comment by Zifrian** [comment]
Is there an error? Selecting multiple facilities is by design. You can't build everything all in the same place unless you are in nullsec sov and have a structure with more than three services, so this is how the program works. 

Setting the base manufacturing facility on the manufacturing tab and saving a facility on the BP tab for a common item like T1 ammo should get about 80% of the items you can build.
