### ISSUE TITLE
shopping list removes extra materials when removing an item

### ISSUE THREAD

**Issue by Regner** [EVEIPH/EVE-IPH#14]
Repro steps:
* Add 200 Light Electron Blaster II's to your shopping list
* Add 50 Griffin's to your shopping list
* Set the Light Electron Blaster II's to 0 quantity in the shopping list
* Notice things such as Tritanium, which is required by the Griffin's, is completely gone. :(

It seems that when removing an item to build from the shopping list it completely removes any materials required for the removed item even if needed by others.

**Comment by Zifrian** [comment]
Hmm, I just put up a fix a few days ago that corrected this and I'm not getting it to happen in the current version. What version of the program are you running? The correct build number is 3.1.5783.13554. I've uploaded the current code edits too. The fix was included in this update: 2dfe088d3111e7a845b4089520eb9a1c6541e507

**Comment by Regner** [comment]
haha I have had the client open for a few days. Will restart it when I get a chance to get the update.
