### ISSUE TITLE
Type 2 BPOs are treated as BPCs

### ISSUE THREAD

**Issue by paulhargreaves** [EVEIPH/EVE-IPH#146]
Version 4.0.7220.39364

I've got a Type 2 BPO in my Manufacturing list ME 10 TE 20.
If I double click it, I get taken to the Blueprints tab but instead of using the properties for the BPO, it's gone in with ME 2 TE 4 and the 'Ignore in Calcs' Invention is unchecked.

This is new behaviour, it used to correctly handle T2 BPOs.

**Comment by Zifrian** [comment]
Ok let me take a look. Can you tell me what bpo it is? Just the name is fine.

Sent from Mail for Windows 10

From: paulhargreaves
Sent: Thursday, October 10, 2019 4:28 PM
To: EVEIPH/EVE-IPH
Cc: Subscribed
Subject: [EVEIPH/EVE-IPH] Type 2 BPOs are treated as BPCs (#146)

Version 4.0.7220.39364
I've got a Type 2 BPO in my Manufacturing list ME 10 TE 20.
If I double click it, I get taken to the Blueprints tab but instead of using the properties for the BPO, it's gone in with ME 2 TE 4 and the 'Ignore in Calcs' Invention is unchecked.
This is new behaviour, it used to correctly handle T2 BPOs.

**Comment by paulhargreaves** [comment]
Try: Dual 150mm Railgun II.

I’ve got both the BPO and some BPCs of it, but it thinks Owned No for the BPCs - which is fine, since I wouldn’t be using them anyway since they’ve got the same stats as the BPO.



If I select the bottom of the 2 entries (the BPO) it shows up like this:

**Comment by Zifrian** [comment]
Any chance this is working now? I tested it out and forced the download data to list a few T2 bpc's I have as bpos and it worked fine. Any chance you had it moved from the character and it picked up the copies instead?

**Comment by paulhargreaves** [comment]
Unfortunately not. I’ve recorded a quick shakey video snippet so you can see me accessing it.
https://www.dropbox.com/s/0pl6lh8whsshdjl/IMG_8157.MOV?dl=0 <https://www.dropbox.com/s/0pl6lh8whsshdjl/IMG_8157.MOV?dl=0>

**Comment by Zifrian** [comment]
Ahh thanks for this. Very helpful. I'll try and get a fix in this weekend.

**Comment by Zifrian** [comment]
Put in a patch. Let me know if it's fixed.

**Comment by aydjay** [comment]
@paulhargreaves Have a look at ShareX if you want to quickly record a gif to share with people.

**Comment by paulhargreaves** [comment]
That appears to have done, thank you.
