### ISSUE TITLE
.NET Framework update

### ISSUE THREAD

**Issue by Pilchard123** [EVEIPH/EVE-IPH#25]
Windows XP is no longer supported by Microsoft, and neither are .NET versions 4.0 and 4.5.1
Windows XP and Windows Vista are in limited support from CCP (the minimum requirements actually specify Windows 7).

Could IPH be updated to .NET 4.5.2 or 4.6.1? It would require dropping IPH support for XP and Vista.

**Comment by Cwittofur** [comment]
I plan to update to .NET 4.5/4.6 within the next release. I need to do some more code analysis to make sure that it wouldn't break functionality (which can be re-coded if lost). The other concern I have would be about Linux support, I know there's a healthy Linux community and want to make sure that it wouldn't break support for them (the user base is unknown at this time).

**Comment by Pilchard123** [comment]
Updating to a later .NET Framework version could remove the dependency on a zip library. 4.5 and up has the [ZipArchive](https://msdn.microsoft.com/en-us/library/system.io.compression.ziparchive(v=vs.110).aspx) class, which may well be able to replace the use of ZipForge/DotNetZip.

**Comment by Zifrian** [comment]
Thanks for the update. Turns out that compression is now stupidly simple to implement. I'll upload the changes to the deployment program first then test out the updater. I think some people will have to get the new version of .Net though, which won't affect windows users (it should prompt them) but Linux will have issues.

**Comment by Zifrian** [comment]
Next patch will have .Net 4.6.
