### ISSUE TITLE
stationid conversion wrong?

### ISSUE THREAD

**Issue by tecxx** [EVEIPH/EVE-IPH#61]
hy,
in EveApi.vb line 898 the comment mentions to substract 6000001
in line 901 actually only 6000000 is substracted.

in an old c# tool i made 5 years ago i used this:
            if (locationID.StartsWith("66"))
                stationID = stationID_temp - 6000001;
            if (locationID.StartsWith("67"))
                stationID = stationID_temp - 6000000;

in other words, i substracted 6000001 and it seemed to be correct at that time.

so which one is correct?

**Comment by Zifrian** [comment]
Thanks for the comment. I was testing some assets and one of my stations came up with a name that I didn't recognize. When I went in to the code I noticed that the number was off by one, so I made this change. I'm wondering if the data was hosed in the last SDE and it's been working fine now. 

I'm going to change it back to the original logic, as you posted above, because it seems to work now and I doubt there was a change like this recently. If someone complains then I'll know it's not working.

**Comment by Zifrian** [comment]
Actually, I'm seeing the issue again. Specifically, the stationID 66015069 (becomes 60015069 after subtracting 6000001, which is Enaluri V - State Protectorate Assembly Plant) from the API doesn't match the station the assets are actually in (Asakai II - State Protectorate Testing Facilities).

Thoughts?

**Comment by tecxx** [comment]
hy,
for me it works correct. when i query 60015069 in dbo.staStations i get:

stationID	security	dockingCostPerVolume	maxShipVolumeDockable	officeRentalCost	operationID	stationTypeID	corporationID	solarSystemID	constellationID	regionID	stationName	x	y	z	reprocessingEfficiency	reprocessingStationsTake	reprocessingHangarFlag
60015069	  0,256374367978025	0	50000000	10000	13	54	1000180	30045332	20000786	10000069	Asakai II - State Protectorate Testing Facilities	11461877760	93265920	82349383680	0,5	0,025	4

i am using your converter tool to create the DB in MSSQL (thanks for that btw)

**Comment by Zifrian** [comment]
Sorry, it becomes 60015068 after subtraction.
